### ISSUE TITLE
Using depay/widgets with Remix.run

### ISSUE THREAD

**Issue by arefay** [DePayFi/widgets#62]
Not sure if this is the right place to ask this question, but wanted to check if anyone has been able to get the @depay/widgets running in a Remix.run project? I'm having little success, for one because there are no typings available, but even skipping those I'm not able to successfully compile the project.

**Comment by spape** [comment]
Any error messages you can share?

**Comment by spape** [comment]
Also if you could setup a test remix app in a fork we could work together on fixing compatibility. 

I suggest you create a `examples/remix` folder and put it in there.

**Comment by arefay** [comment]
Thank you for getting back to me. I've created a bare-bones remix.run app where I'm trying to load the Depay donation widget. You can see/clone it from here: [https://github.com/arefay/remix-depay](https://github.com/arefay/remix-depay)

Once you run it you'll see the build errors. Apologies upfront, I'm not the most experienced dev so maybe this is something simple I'm missing, but I'm a bit stuck and would love to solve and use Depay widgets for my next project.

**Comment by arackaf** [comment]
These are the errors. 

Possibly a problem on Remix's side. 

<img width="986" alt="image" src="https://user-images.githubusercontent.com/11261266/184278735-1f169fff-0ed9-47c1-8560-f258dafef946.png">

**Comment by arackaf** [comment]
This appears to be the relevant issue in Remix. The root problem is that @depay/widgets imports some other @depay/ utilities, which themselves import "buffer" and some other node built-ins, which Remix doesn't seem to like. 

https://github.com/remix-run/remix/issues/114

**Comment by arackaf** [comment]
Chance's comment here is illuminating. It sounds like this is a known issue with Remix, and it doesn't sound like there's any kind of fix.

@spape is there any kind of clever way @arefay could somehow import these @depay widgets, without bringing buffer (or any other Node globals) along in the import graph? 

Else I think moving to Next might be the only way forward for him :-| 

https://github.com/remix-run/remix/issues/2248#issuecomment-1092847237

**Comment by spape** [comment]
@arackaf @arefay 
It's not about not bringing buffer and other Node globals into the mix. It's also not DePay's libraries that do that, that's only where the stack trace gets you. It's the libraries under the DePay libraries that bring them into the mix. Often it's very low level crypto js libraries that do that (because they want to support browser and node 🤦). And then remix loads `.esm` packages which are preferred by node (server side or eg node best testing frameworks like jest) not providing node globals, JavaScript development remains a huge mess.

The trick is to use a bundled version, see working example here: https://github.com/spape/remix-depay/commit/cc136a13a6f89685e16fc8af99ff0dde5b420800

https://user-images.githubusercontent.com/851393/184298661-a6fef82a-27ab-4f77-9ac9-2b7b18cf79fa.mov

**Comment by arackaf** [comment]
@spape oof - thanks a ton! I actually poked around those UMD builds, but I didn't think they'd work. The umd build for web3-client made the same import (via require) on buffer, so I assumed it would similarly fail.

Thanks so much for debugging this though! 

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/11261266/184353790-8ddfe7ee-3a3f-4f8c-af2c-79825b96d5f7.png">

**Comment by arefay** [comment]
Thanks so much @spape and @arackaf for your help with this. Works great now!
